### ISSUE TITLE
Update Version of react-dnd-html5-backend

### ISSUE THREAD

**Issue by reece-berens** [lifejuggler/react-cat-tree#2]
With the latest update (0.0.2), the version of react-dnd was updated to 11.1.3, but the react-dnd-html5-backend package also needs to be updated to 11.1.3. This should help prevent the following error:
![image](https://user-images.githubusercontent.com/23461315/88306512-7071ee00-ccd0-11ea-9ed4-70e4d6d07cc9.png)

[This pull request](https://github.com/frontend-collective/react-sortable-tree/pull/747) on the react-sortable-tree package, which I believe the author of this package is trying to mimick, uses the latest version (11.1.3) of react-dnd-html5-backend.

**Comment by lifejuggler** [comment]
Thanks, I made an update and publishing version 0.0.3.
